In [10]:
from numpy import array
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.embeddings import Embedding
# define documents
docs = ['Well done!',
        'Good work',
        'Great effort',
        'nice work',
        'Excellent!',
        'Weak',
        'Poor effort!',
        'not good',
        'poor work',
        'Could have done better.']
# define class labels
labels = array([1,1,1,1,1,0,0,0,0,0])
# integer encode the documents
vocab_size = 50
encoded_docs = [one_hot(d, vocab_size) for d in docs]
print(encoded_docs)
# pad documents to a max length of 4 words
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)
# define the model
model = Sequential()
model.add(Embedding(vocab_size, 8, input_length=max_length))
# summarize the model
print(model.summary())
# fit the model
model.fit(padded_docs, labels, epochs=50, verbose=0)
# evaluate the model
loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print('Accuracy: %f' % (accuracy*100))

[[25, 44], [29, 43], [29, 41], [45, 43], [17], [47], [13, 41], [49, 29], [13, 43], [35, 14, 44, 23]]
[[25 44  0  0]
 [29 43  0  0]
 [29 41  0  0]
 [45 43  0  0]
 [17  0  0  0]
 [47  0  0  0]
 [13 41  0  0]
 [49 29  0  0]
 [13 43  0  0]
 [35 14 44 23]]
Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_7 (Embedding)      (None, 4, 8)              400       
Total params: 400
Trainable params: 400
Non-trainable params: 0
_________________________________________________________________
None


RuntimeError: You must compile a model before training/testing. Use `model.compile(optimizer, loss)`.